### ISSUE TITLE
Pins holding their default high or low pull

### ISSUE THREAD

**Issue by michaelwschultz** [adafruit/Pi_Node_Example#1]
For some reason just getting blink.js to light up the light is giving me issues. It seems like the script isn't overriding the default state of the pins. If I plug my LED into pin 17 or 5 it turns on because those pins are set to high by default I believe when the Pi boots. Running this script on those pins also outputs 1111 rather than 1010 and the light just stays on. On pins that aren't high to begin, the output is correct but the LED never lights. Any ideas here? I'm running a Pi 3 Model B. Thanks!

**Comment by ladyada** [comment]
hiya this repo is not being maintained so we will be archiving it!
